<?php

return [

    '/' => ['Home', 'projeto'],
    '/home' => ['Home', 'index'],
    '/projeto' => ['Home', 'index'],
    '/projeto/' => ['Home', 'index'],
    '/home/index' => ['Home', 'index'],
    '/home/planos' => ['Home', 'planos'],
    '/home/recursos' => ['Home', 'recursos'],
    '/home/contato' => ['Home', 'contato'],

    '/usuarios' => ['Usuarios', 'index'],
    '/usuarios/new' => ['Usuarios', 'new'],
    '/usuarios/index' => ['Usuarios', 'index'],
    '/usuarios/edit/{id}' => ['Usuarios', 'edit'],
    '/usuarios/delete/{id}' => ['Usuarios', 'delete'],
    '/usuarios/save' => ['Usuarios', 'save'],
    '/usuarios/edit_save' => ['Usuarios', 'edit_save'],
    '/usuarios/search' => ['Usuarios', 'search'],

    '/login' => ['Login', 'index'],
    '/login/index' => ['Login', 'index'],
    '/login/auth' => ['Login', 'auth'],
    '/login/logout' => ['Login', 'logout'],
    
   
    '/admin'                     => ['Admin', 'index'],
    '/admin/usuarios'            => ['Admin', 'usuarios'],
    '/admin/usuarios/edit'       => ['Admin', 'usuarios_edit'],   
    '/admin/usuarios/update'     => ['Admin', 'usuarios_update'],
    '/admin/barbearias'          => ['Admin', 'barbearias'],
    '/admin/barbearias/new'      => ['Admin', 'barbearias_new'],    
    '/admin/barbearias/create'   => ['Admin', 'barbearias_create'], 
    '/admin/barbearias/view'     => ['Admin', 'barbearias_view'],   
    '/admin/barbearias/edit'     => ['Admin', 'barbearias_edit'],   
    '/admin/barbearias/update'   => ['Admin', 'barbearias_update'], 
    '/admin/barbearias/status'   => ['Admin', 'barbearias_status'], 
    '/admin/planos'              => ['Admin', 'planos'],
    '/admin/planos/save'         => ['Admin', 'planos_save'],
    '/admin/planos/delete'       => ['Admin', 'planos_delete'],
    '/admin/financeiro'          => ['Admin', 'financeiro'],
    '/admin/configuracoes'       => ['Admin', 'configuracoes'],
        
    '/dono' => ['Dono', 'index'],
    '/dono/equipe' => ['Dono', 'equipe'],
    '/dono/agenda' => ['Dono', 'agenda'],
    '/dono/agenda/new' => ['Dono', 'agenda_new'],
    '/dono/agenda/save' => ['Dono', 'agenda_save'],
    '/dono/servicos' => ['Dono', 'servicos'],
    '/dono/configuracoes' => ['Dono', 'configuracoes'],
    '/dono/configuracoes/save' => ['Dono', 'configuracoes_save'],
    '/dono/visagismo' => ['Dono', 'visagismo'],
    '/dono/equipe/new' => ['Dono', 'equipe_new'],
    '/dono/equipe/save' => ['Dono', 'equipe_save'],
    '/dono/equipe/edit' => ['Dono', 'equipe_edit'],
    '/dono/equipe/update' => ['Dono', 'equipe_update'],
    '/dono/servicos/new' => ['Dono', 'servicos_new'],
    '/dono/servicos/edit' => ['Dono', 'servicos_edit'],
    '/dono/servicos/update' => ['Dono', 'servicos_update'],
    '/dono/servicos/save' => ['Dono', 'servicos_save'],
    
    '/barbeiro' => ['Barbeiro', 'index'],
    '/barbeiro/equipe' => ['Barbeiro', 'equipe'],
    '/barbeiro/agenda' => ['Barbeiro', 'agenda'],
    '/barbeiro/agenda/new' => ['Barbeiro', 'agenda_new'],
    '/barbeiro/agenda/save' => ['Barbeiro', 'agenda_save'],
    '/barbeiro/servicos' => ['Barbeiro', 'servicos'],
    '/barbeiro/configuracoes' => ['Barbeiro', 'configuracoes'],
    '/barbeiro/configuracoes/save' => ['Barbeiro', 'configuracoes_save'],
    '/barbeiro/servicos/new' => ['Barbeiro', 'servicos_new'],
    '/barbeiro/servicos/save' => ['Barbeiro', 'servicos_save'],
    '/barbeiro/visagismo' => ['Barbeiro', 'visagismo'],
    '/barbeiro/visagismo_analisar' => ['Barbeiro', 'visagismo_analisar'],

];